ARCHS = arm64
TARGET = iphone:clang:latest:14.0
INSTALL_TARGET_PROCESSES = Rhus
APPLICATION_NAME = Rhus

Rhus_FILES = Sources/ContentView.swift Sources/Rhus.swift
Rhus_EXTRA_FRAMEWORKS = Chrissa

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/application.mk
