ARCHS = arm64
TARGET = iphone:clang:17.4:15.0
INSTALL_TARGET_PROCESSES = Rhus
APPLICATION_NAME = Rhus

Rhus_FILES = $(wildcard */**/**.swift)
Rhus_EXTRA_FRAMEWORKS = Chrissa

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/application.mk
